apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volumeclaim
  namespace: WebApplication
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: mysqldata
