apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: api
  name: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: "hbsuhas/node:1.0"
          name: nodejs
          ports:
            - containerPort: 3000
              name: nodejs
